name: Deploy Infrastructure with Terraform

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.tf'

permissions:
  id-token: write
  contents: read
  pull-requests: write 

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    outputs:
      tfplan_path: steps.plan.outputs.plan_path
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ap-northeast-2

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan.binary
      
      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan.binary
          
  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan # plan 잡이 성공해야 실행됨
    
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ap-northeast-2
          
      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          
      - name: Terraform Init
        id: init
        run: terraform init
        
      - name: Terraform Apply
        id: apply
        run: terraform apply -input=false tfplan.binary


